# Generated by Django 3.2.9 on 2021-12-13 19:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211212_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='request_out',
            field=models.ManyToManyField(blank=True, related_name='request_in', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='FriendRequest',
        ),
    ]
