# Generated by Django 3.2.9 on 2021-12-16 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_competition_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='competition_points',
        ),
    ]
