# Generated by Django 3.2.9 on 2021-12-06 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='uuid',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
