# Generated by Django 3.2.9 on 2021-12-06 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_exercise_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('exercises', models.ManyToManyField(related_name='categories', to='exercises.Exercise')),
            ],
        ),
    ]
