# Generated by Django 3.2.9 on 2021-12-06 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='exercises',
            field=models.ManyToManyField(related_name='categorys', to='exercises.Exercise'),
        ),
    ]
