# Generated by Django 3.2.9 on 2021-12-07 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0005_remove_exercise_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='exercises',
            field=models.ManyToManyField(related_name='categoryies', to='exercises.Exercise'),
        ),
    ]
