# Generated by Django 3.2.9 on 2021-12-07 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0009_rename_history_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='name',
            field=models.CharField(default='New Workout', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='session',
            name='exercises',
            field=models.ManyToManyField(related_name='sessions', to='exercises.Exercise'),
        ),
    ]
