# Generated by Django 3.2.9 on 2021-12-08 00:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercises', '0010_auto_20211207_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='user',
        ),
        migrations.AddField(
            model_name='session',
            name='user',
            field=models.ManyToManyField(related_name='sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
