# Generated by Django 3.2.9 on 2021-12-08 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0011_auto_20211207_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set', models.IntegerField()),
                ('reps', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.exercise')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.session')),
            ],
        ),
    ]
