# Generated by Django 3.2.9 on 2021-12-08 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0012_exerciseinstance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='exercises',
        ),
    ]
