# Generated by Django 3.2.9 on 2021-12-08 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0013_remove_session_exercises'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='exercises',
            field=models.ManyToManyField(related_name='sessions', to='exercises.Exercise'),
        ),
    ]
