# Generated by Django 3.2.9 on 2021-12-08 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0014_session_exercises'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseinstance',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='exercises.session'),
        ),
    ]
