# Generated by Django 3.2.9 on 2021-12-08 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0015_alter_exerciseinstance_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='exercises',
        ),
    ]
