# Generated by Django 3.2.9 on 2021-12-08 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0018_auto_20211208_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setinstance',
            name='exerciseinstance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setinstance', to='exercises.exerciseinstance'),
        ),
    ]
