# Generated by Django 3.2.9 on 2021-12-08 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0020_auto_20211208_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setinstance',
            name='exerciseinstance',
        ),
        migrations.AddField(
            model_name='exerciseinstance',
            name='setinstance',
            field=models.ManyToManyField(related_name='exerciseinstance', to='exercises.SetInstance'),
        ),
    ]
