# Generated by Django 3.2.9 on 2021-12-08 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0021_auto_20211208_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciseinstance',
            name='setinstance',
        ),
        migrations.AddField(
            model_name='setinstance',
            name='exerciseinstance',
            field=models.ManyToManyField(related_name='setinstance', to='exercises.ExerciseInstance'),
        ),
    ]
