# Generated by Django 3.2.9 on 2021-12-10 17:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercises', '0022_auto_20211208_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('exercecises', models.ManyToManyField(related_name='temp_exercises', to='exercises.Exercise')),
                ('user', models.ManyToManyField(related_name='templates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
