# Generated by Django 3.2.9 on 2021-12-11 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0025_rename_exercecises_workouttemplate_exercises'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='name',
        ),
    ]
