# Generated by Django 3.2.9 on 2021-12-13 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0028_competition_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='setinstance',
            name='comp_points',
            field=models.IntegerField(default=0),
        ),
    ]
