# Generated by Django 3.2.9 on 2021-12-13 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0030_competition_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setinstance',
            name='comp_points',
        ),
    ]
