# Generated by Django 3.2.9 on 2021-12-13 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0031_remove_setinstance_comp_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='setinstance',
            name='comp_points_per_set',
            field=models.IntegerField(default=0),
        ),
    ]
