# Generated by Django 3.2.9 on 2021-12-13 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0033_rename_comp_points_per_set_setinstance_set_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='sessions',
            field=models.ManyToManyField(related_name='competition', to='exercises.Session'),
        ),
    ]
