# Generated by Django 3.2.9 on 2021-12-14 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0035_auto_20211213_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='competition',
            field=models.ManyToManyField(blank=True, related_name='sessions', to='exercises.Competition'),
        ),
    ]
