# Generated by Django 3.2.9 on 2021-12-14 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0036_alter_session_competition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setinstance',
            name='set_points',
        ),
        migrations.AddField(
            model_name='exerciseinstance',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
