# Generated by Django 3.2.9 on 2021-12-14 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0038_exercise_exercise_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='exercise_points',
        ),
        migrations.AddField(
            model_name='competition',
            name='exercise_point_value',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='exercises.exercise'),
            preserve_default=False,
        ),
    ]
