# Generated by Django 3.2.9 on 2021-12-14 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0039_auto_20211214_0700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='exercise_point_value',
        ),
    ]
