# Generated by Django 3.2.9 on 2021-12-14 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0040_remove_competition_exercise_point_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_points', models.IntegerField(default=0)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.exercise')),
            ],
        ),
        migrations.AlterField(
            model_name='competition',
            name='exercises',
            field=models.ManyToManyField(related_name='competition_exercises', to='exercises.CompExercise'),
        ),
    ]
