# Generated by Django 3.2.9 on 2021-12-14 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0041_auto_20211214_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='exercises',
        ),
        migrations.AddField(
            model_name='compexercise',
            name='competition',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='exercises.competition'),
            preserve_default=False,
        ),
    ]
