# Generated by Django 3.2.9 on 2021-12-16 23:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercises', '0044_usercompscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercompscore',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='exercises.competition'),
        ),
        migrations.AlterField(
            model_name='usercompscore',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to=settings.AUTH_USER_MODEL),
        ),
    ]
