# Generated by Django 3.2.9 on 2021-12-19 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0045_auto_20211216_1515'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercompscore',
            options={'ordering': ['-score']},
        ),
    ]
