# Generated by Django 3.2.9 on 2021-12-21 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0046_alter_usercompscore_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
