# Generated by Django 4.0 on 2021-12-21 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0047_alter_session_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='description',
            field=models.CharField(max_length=600),
        ),
    ]
